name: GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup env
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 14.x
          cache: "yarn"

      # Install deps
      - name: Install Dependencies
        run: yarn --frozen-lockfile

      # Build
      - name: Build
        run: yarn build

      # Deploy
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: gh-pages
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
