name: GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup env
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 14.x
          cache: "yarn"

      # Install deps
      - name: Install Dependencies
        run: yarn --frozen-lockfile

      # Build
      - name: Build
        run: yarn build

      # Deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_dir: ./dist
          force_orphan: true
